name: Build Android APK 
 
on: 
  push: 
    branches: [ main ] 
  pull_request: 
    branches: [ main ] 
 
jobs: 
  build: 
    runs-on: ubuntu-latest 
     
    steps: 
    - uses: actions/checkout@v4 
     
    - name: Set up JDK 17 
      uses: actions/setup-java@v4 
      with: 
        java-version: '17' 
        distribution: 'temurin' 
         
    - name: Setup Android SDK 
      uses: android-actions/setup-android@v3 
       
    - name: Accept Android SDK licenses 
      run: yes | sdkmanager --licenses 
       
    - name: Install SDK 34 
      run: sdkmanager "platforms;android-34" "build-tools;34.0.0" 
       
    - name: Build with Gradle 
      run: ./gradlew assembleDebug 
       
    - name: Upload APK 
      uses: actions/upload-artifact@v4 
      with: 
        name: app-debug.apk 
        path: app/build/outputs/apk/debug/app-debug.apk 

